## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
# Q1-1
print("Q1-1")
import pandas as pd
df = pd.DataFrame(data)
print(df, "\n")

# Q1-2
print("\nQ1-2")
occupation =  [(df['job'] == 'teacher') | (df['job'] == 'psychologist')] 
cars = df.num_cars > df.family_size 
print(occupation, cars)

# Q1-3
print("\nQ1-3")
result = df[(df.num_cars >= 1) & (df.family_size <= 2)]
print(result)

# Q1-4
print("\nQ1-4")
print(len(df['job'].unique()))

Q1-1
     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1 


Q1-2
[0     True
1     True
2    False
3    False
4     True
5     True
6     True
Name: job, dtype: bool] 0    False
1    False
2    False
3    False
4    False
5     True
6    False
dtype: bool

Q1-3
    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1

Q1-4
4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))


In [ ]:
# group fruits by each name and find the means of the weight series
weights.groupby(fruit).mean()


apple     6.500000
banana    5.600000
carrot    4.666667
dtype: float64

**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
print("Q3-1")
indices = np.argsort(course_name)
print(indices)

print("\nQ3-2")
list = course_name.tolist()
for course in list:
  if course.lower().startswith("p"):
    print(course)


Q3-1
[1 3 0 2 4]

Q3-2
Python
PHP


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
print("Q4-1")
print(student_id)
print(student_id[::-1])

print("\nQ4-2")
array = np.sort(student_id)
descendingArray = array[::-1]
print(descendingArray[0:3])



Q4-1
[1023 5202 6230 1671 1682 5241 4532]
[4532 5241 1682 1671 6230 5202 1023]

Q4-2
[6230 5241 5202]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# import numpy 
import numpy as np
# arrange numbers from 1 - 99
numbers = np.arange(1, 100)
# find  multiples of 3 or 5
multiples = numbers[(numbers % 3 == 0) | (numbers % 5 == 0)]
# print sum of the multiples 
print(multiples.sum())

2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print("Q6-1")
arr[:, [2, 1]] = arr[:, [1, 2]]
print(arr)

print("\nQ6-2")
arr[[1, 0],:] = arr[[0, 1],:]
print(arr)

Q6-1
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]

Q6-2
[[ 4  6  5  7]
 [ 0  2  1  3]
 [ 8 10  9 11]]
